Repository squirrel-labs/ratatosk, pull requests merged in 2020-04, with the labels that each got.

#56 Implement core engine structure
  .gitignore
  Cargo.lock
  client/graphics/src/graphics.rs
  client/shared/src/error.rs
  client/shared/src/lib.rs
  client/shared/src/mem.rs
  rask-engine/Cargo.toml
  rask-engine/src/boxes.rs
  rask-engine/src/collide.rs
  rask-engine/src/error.rs
  rask-engine/src/lib.rs
  rask-engine/src/math/mat3.rs
  rask-engine/src/math/vec2.rs
  rask-engine/src/math/vec3.rs
  rask-engine/src/math_simd/mat2.rs
  rask-engine/src/math_simd/mod.rs
  rask-engine/src/math_simd/vec2.rs
  rask-engine/src/resources/library.rs
  rask-engine/src/resources/mod.rs
  rask-engine/src/resources/sound.rs
  rask-engine/src/resources/texture.rs
  rask-engine/src/webhogg_game.rs
  rask-engine/src/webhogg_player.rs
  rask-engine/src/world.rs
  rask-engine/tests/collide_test.rs
  rask-engine/tests/vec2.rs
  rask-engine/tests/vec3.rs
Labels: engine

#49 Rework scheduling on frontend
  .drone.yml
  Cargo.lock
  Cargo.toml
  Makefile.toml
  client/Makefile.toml
  client/double-buffer/Cargo.toml
  client/double-buffer/src/lib.rs
  client/double-buffer/tests/integration.rs
  client/gen_mem_layout.rs
  client/graphics/Cargo.toml
  client/graphics/src/context.rs
  client/graphics/src/entries.rs
  client/graphics/src/graphics.rs
  client/graphics/src/lib.rs
  client/graphics/src/render.rs
  client/graphics/src/shader/fragment.glsl
  client/graphics/src/shader/vertex.glsl
  client/index.html
  client/logic/Cargo.toml
  client/logic/src/entries.rs
  client/logic/src/game_context.rs
  client/logic/src/lib.rs
  client/res/thief.png
  client/shared/Cargo.toml
  client/shared/build.rs
  client/shared/src/alloc.rs
  client/shared/src/double_buffer.rs
  client/shared/src/error.rs
  client/shared/src/lib.rs
  client/shared/src/mem.rs
  client/shared/src/message_queue.rs
  client/shared/src/sprite.rs
  client/shared/src/state.rs
  client/site/main.js
  client/site/worker.js
  rask-engine/Cargo.toml
  rask-engine/benches/bench.rs
  rask-engine/src/collide.rs
  rask-engine/src/error.rs
  rask-engine/src/events.rs
  rask-engine/src/lib.rs
  rask-engine/src/math/mat3.rs
  rask-engine/src/resources/character.rs
  rask-engine/src/resources/library.rs
  rask-engine/src/resources/mod.rs
  rask-engine/src/resources/registry.rs
  rask-engine/src/resources/resource_table.rs
  rask-engine/src/resources/texture.rs
  rask-engine/src/world.rs
  rask-server/Cargo.toml
  rask-server/src/backend_connection.rs
  rask-server/src/error.rs
  rask-server/src/games.rs
  rask-server/src/group.rs
  rask-server/src/server.rs
  tools/bone-cake/Cargo.toml
  tools/bone-cake/src/character.rs
  tools/bone-cake/src/main.rs
  tools/bone-cake/src/structs.rs
  tools/bone-cake/src/textures.rs
Labels: frontend, performance

#70 Fix ci workflow
  .drone.yml
Labels: infra
